### PR TITLE
Tag 0.9.23

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by mudler** [comment]
sorry, didn't saw it!

**Comment by Itxaka** [comment]
wrong window

**Comment by mudler** [comment]
needs to be 0.9.24

**Comment by Itxaka** [comment]
@mudler why? latest in yip is .23 no?

**Comment by mudler** [comment]
https://github.com/mudler/yip/commit/35f13de355e55483654f833152742ce67e2baa14 :sweat_smile:

**Comment by Itxaka** [comment]
oh you sneaky bastard!

**Pull request closed without merging**
