### PR TITLE
Use shlex.Split to split dotNotation files

### PR DESCRIPTION
**Pull request by Itxaka**
Currently if we try to load a dotNotation file and that file has spaces
in them, i.e. commands in quotes, it will panic and fail to load.

This patch changes the split of the file to use shlex which is context
aware of quotes and preserves that as one item insteaed of splitting it
further thus avoiding strange parsing like ">:true" which gojq fails to
parse completely.

Alos adds some tests for malformed files and half malformed files

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by mudler** [comment]
Looks good here, but I'd also add a check on https://github.com/mudler/yip/blob/master/pkg/schema/schema.go#L240 to avoid panic'ing if the assertion fails there

**Comment by Itxaka** [comment]
to be fair, I have no idea of what ` v.(map[string]interface{})` does in there?? Is it casting `v` into a `map[string]interface{}` type??

**Comment by mudler** [comment]
yep, exactly. Golang panics in that case as we do an assertion without checking if it's actually of that type, like we do instead here: https://github.com/mudler/yip/blob/master/pkg/schema/schema.go#L237

**Comment by Itxaka** [comment]
Done!

**Comment by mudler** [comment]
uh, tests are failing for the golang version :/

**Comment by mudler** [comment]
seems tests are still running on go 1.14.x :roll_eyes: https://github.com/mudler/yip/blob/master/.github/workflows/test.yml#L7

**Comment by Itxaka** [comment]
ok, bumped the go version to 1.16 :D

Autobumper for go version in the workflows when? :P

**Review by mudler — APPROVED** [review]

**Pull request merged**
