### PR TITLE
Parse VMWARE provider userdata 

### PR DESCRIPTION
**Pull request by Itxaka**
VMWARE provider userdata brings the userdata with a multipart/mixed
content instead of plain text.

This patch makes it so we try to parse the multipart message and extract
the cloud config from the userdata in case it comes from the vmware
provider

This requires a patch to linuxkit in order to make the vmware provider work as currently is not working: https://github.com/rancher-sandbox/linuxkit/pull/3

Signed-off-by: Itxaka <itxaka@kairos.io>

### CODE REVIEW

**Review by mudler — APPROVED** [review]
looking good!

**Comment by sarg3nt** [comment]
Hi @Itxaka , do you know when this might get merged and once merged when I might see it in an alpha?

**Comment by Itxaka** [comment]
> Hi @Itxaka , do you know when this might get merged and once merged when I might see it in an alpha?

Hey @sarg3nt this needs an upstream patch before merging from https://github.com/rancher-sandbox/linuxkit/pull/3 and I think the maintainer is currently on vacation.

I'm also on vacation so when I'm back I will check with him to see if he's back

**Comment by Itxaka** [comment]
Upstream patch merged.

The issues in the tests for this patch seem to not be related to the actual change. Ssh tests seems flimsy to me.

Also needs a bump to deps to include latest linuxkit with the fixed VMware provider.

I'm back on Friday if this is still as is, will update it .

**Comment by sarg3nt** [comment]
Hi @Itxaka , thanks for getting this merged in.  I'm out on vacation until the 20th so I won't be able to test until I get back.  Sorry about that.  Taking the family to Puerto Vallarta for a couple weeks.

**Comment by Itxaka** [comment]
> Hi @Itxaka , thanks for getting this merged in.  I'm out on vacation until the 20th so I won't be able to test until I get back.  Sorry about that.  Taking the family to Puerto Vallarta for a couple weeks.  
>  

Enjoy!

**Pull request merged**
